Add include paths to input root tree
Currently the CcCompile action would works like this:

```
inputs --( CcCompile )--> output.{d,o}
output.d --( Bazel's Verify Import )--> verify result
```

The import verification step helps warn us of paths which was used in
the compilation, but was not explicitly declared in Bazel's starlark,
either in build target's deps or in toolchain's path. A fail
verification might look like this:

```
ERROR: absolute path inclusion(s) found in rule '@@abseil-cpp~//absl/base:spinlock_wait':
the source file 'absl/base/internal/spinlock_wait.cc' includes the following non-builtin files with absolute paths (if these are builtin files, make sure these paths are in your toolchain):
  '/usr/lib/gcc/aarch64-linux-gnu/11/include/stdint.h'
  '/usr/lib/gcc/aarch64-linux-gnu/11/include/limits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/11/include/syslimits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/11/include/stddef.h'
```

Currently our toolchain indicated that some of these paths, such as
`/usr/lib/gcc/aarch64-linux-gnu/11/include` should be ignored
by the verification step. However, when these paths are changed, we do
not invalidate the previous CcCompile action as they are not declared in
the Command's arguments (gcc flags) or the input root tree. This could
cause some confusion when user try to tweak these import paths and ran
into potential inaccurate cached result.

Solve this problem by writing these paths into a text file and include
the text file as part of the input root tree as a dependency of our
toolchain. This way, any updates to these paths should also invalidate
the compilation action.

Fix similar issue in the msvc setup.